apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-auto-mode
  resources:
    requests:
      storage: 10Gi