apiVersion: v1
kind: Service
metadata:
  name: vmagent
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: victoria-agent
    app.kubernetes.io/instance: vmagent
  ports:
  - port: 8429
    targetPort: 8429
    name: http
  type: ClusterIP
