apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
      - name: prometheus-app
        image: ved104/prom-functions:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PUSHGATEWAY_URL
          value: "http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
        - name: PUSH_INTERVAL
          value: "15"
        - name: JOB_NAME
          value: "prometheus-functions"
        - name: ALLOY_ENDPOINT
          value: "alloy.monitoring.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "fastapi-telemetry-app"