apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: prometheus-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
