apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-app-sm
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-app
  namespaceSelector:
    matchNames:
      - default   # namespace of the deployment
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
