apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-app-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: prometheus-app
  targetLabels:
    - app
  namespaceSelector:
    matchNames:
      - default # this tells as the to watch in the default namespac also beasue the ServiceMonitor is like it looks only in its own namespace 
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
