apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-auto-mode
  resources:
    requests:
      storage: 5Gi


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data  #<-- this is the Pod path that will be mounted
          subPath: pgdata # <-- here the EBC volume is mounted
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc